### ISSUE TITLE
Dependabot alerts

### ISSUE THREAD

**Issue by nega0** [icecube/NuCat#14]
Glad to see the repo using GitHub features like Dependabot, but let's do something about the alerts. Otherwise, if NuCat is "finished" let's disable Dependabot, and put the repo in archive mode.

**Comment by ChujieChen** [comment]
The repo's Dependabot alerts have been disabled. All future dependencies alerts will be addressed within the forked [repo](https://github.com/ChujieChen/NuCat) and commits will be PRed into this repo.
